allow-uncaught: false
async-only: false
bail: false
check-leaks: false
color: true
delay: false
diff: true
exit: true # could be expressed as "no-exit: true"
extension:
  - 'js'
# fgrep and grep are mutually exclusive
# fgrep: something
file:
  - './'
forbid-only: false
forbid-pending: false
full-trace: false
global:
  - 'global'
# fgrep and grep are mutually exclusive
# grep: something
growl: false
ignore:
  - 'node_modules/**'
inline-diffs: false
# needs to be used with grep or fgrep
# invert: false
recursive: false
reporter: 'spec'
reporter-option:
  - 'foo=bar'
  - 'baz=quux'
# require: '@babel/register'
retries: 0
slow: 45
sort: false
spec: '**/*.spec.js' # the positional arguments!
timeout: 0 # same as "no-timeout: true"
trace-warnings: true # node flags ok
ui: 'bdd'
v8-stack-trace-limit: 100 # V8 flags are prepended with "v8-"
watch: false
watch-files:
  - './web/**/*.js'
watch-ignore:
  - 'node_modules/'
