# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: 14.x

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Setup NPM Auth
      run: |
        echo '${{ env.NEXUS_NPMRC }}' > ./.npmrc
        echo '${{ env.NEXUS_YARNRC }}' > ./.yarnrc

    - name: Test
      run: |
        yarn install
        yarn run test
      env:
        FAKE_REDIS: 'true'

    - name: Publish
      run: npm pub

env:
  NEXUS_NPMRC: '${{ secrets.NEXUS_NPMRC }}'
  NEXUS_YARNRC: '${{ secrets.NEXUS_YARNRC }}'
